# vanilla splade with mistral rewrites on TOPIOCQA
config:
  lr: 2.0e-05
  seed: 123
  gradient_accumulation_steps: 1
  weight_decay: 0.01
  validation_metrics:
  - MRR@10
  - recall@100
  - recall@200
  - recall@500
  - ndcg@3
  - ndcg@5
  - ndcg@10
  - ndcg@100
  pretrained_no_yamlconfig: false
  nb_iterations: 150000
  train_batch_size: 10
  eval_batch_size: 64
  index_retrieve_batch_size: 64
  record_frequency: 10000
  train_monitoring_freq: 500
  warmup_steps: 6000
  max_length: 256
  fp16: true
  matching_type: splade
  monitoring_ckpt: MRR@10
  tokenizer_type: Luyu/co-condenser-marco
  top_k: 1000
  threshold: 0
  eval_metric:
  - - mrr_10
    - mrr_1000
    - recall
    - ndcg@3
  retrieval_name:
  - QRECC
  regularizer:
    FLOPS:
      lambda_d: 0
      targeted_rep: rep
      reg: FLOPS
    L1:
      lambda_q: 0
      targeted_rep: rep
      reg: L1
  checkpoint_dir: ??
  index_dir: ??
  out_dir: ??
  config.lr: 2.0e-05
data:
  type: json
  COLLECTION_PATH: /scratch-shared/disco/DATA/full_wiki_segments_topiocqa.tsv
  Q_COLLECTION_PATH:
  - /scratch-shared/disco/DATA/qrecc/human_rewrites_dev.tsv
  EVAL_QREL_PATH:
  - /scratch-shared/disco/DATA/qreccs/qrels_rowid_dev.json
  flops_queries: /scratch-shared/disco/DATA/qrecc/human_rewrites_dev.tsv
init_dict:
  model_type_or_dir: naver/splade-cocondenser-ensembledistil
  model_type_or_dir_q: naver/splade-cocondenser-ensembledistil
  freeze_d_model: 1
  agg: max
  fp16: true
hf:
  model:
    dense: false
    shared_weights: false
  data:
    distillation: false
    n_negatives: 16
    wandb_project_name: disco-conv-splade
    wandb_run_name: disco_qrecc_human_rewrites
  